# Generated by Django 5.2.7 on 2025-10-25 14:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la cuenta (ej: 1.1.01)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la cuenta', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la cuenta')),
                ('nivel', models.IntegerField(default=1, help_text='Nivel en la jerarquía del plan de cuentas')),
                ('tipo_cuenta', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], help_text='Tipo de cuenta según clasificación contable', max_length=20)),
                ('naturaleza', models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], help_text='Naturaleza de la cuenta (Deudora o Acreedora)', max_length=10)),
                ('_saldo', models.DecimalField(db_column='saldo', decimal_places=2, default=Decimal('0.00'), help_text='Saldo actual de la cuenta', max_digits=15)),
                ('es_cuenta_detalle', models.BooleanField(default=True, help_text='Si es True, permite movimientos. Si es False, solo agrupa subcuentas')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la cuenta está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, help_text='Cuenta padre en la jerarquía', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='accounting.cuentacontable')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_contables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cuenta (Legacy)', 'verbose_name_plural': 'Cuentas (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'name'], 'verbose_name': 'Categoría (Legacy)', 'verbose_name_plural': 'Categorías (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-created_at'], 'verbose_name': 'Transacción (Legacy)', 'verbose_name_plural': 'Transacciones (Legacy)'},
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('cuentacontable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.cuentacontable')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'proxy': False,
            },
            bases=('accounting.cuentacontable',),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('cuentacontable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.cuentacontable')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'proxy': False,
            },
            bases=('accounting.cuentacontable',),
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('cuentacontable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.cuentacontable')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'proxy': False,
            },
            bases=('accounting.cuentacontable',),
        ),
        migrations.CreateModel(
            name='Pasivo',
            fields=[
                ('cuentacontable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.cuentacontable')),
            ],
            options={
                'verbose_name': 'Pasivo',
                'verbose_name_plural': 'Pasivos',
                'proxy': False,
            },
            bases=('accounting.cuentacontable',),
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('cuentacontable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.cuentacontable')),
            ],
            options={
                'verbose_name': 'Patrimonio',
                'verbose_name_plural': 'Patrimonio',
                'proxy': False,
            },
            bases=('accounting.cuentacontable',),
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único del asiento (ej: AS-2025-001)', max_length=20, unique=True)),
                ('fecha', models.DateField(help_text='Fecha del asiento contable')),
                ('descripcion', models.TextField(help_text='Descripción detallada del asiento')),
                ('referencia', models.CharField(blank=True, help_text='Referencia externa (número de factura, recibo, etc.)', max_length=100)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REGISTRADO', 'Registrado'), ('ANULADO', 'Anulado')], default='BORRADOR', help_text='Estado actual del asiento', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_registro', models.DateTimeField(blank=True, help_text='Fecha y hora en que se registró el asiento', null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, help_text='Fecha y hora en que se anuló el asiento', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que creó el asiento', on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del débito', max_digits=15)),
                ('credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto del crédito', max_digits=15)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción específica de este movimiento', max_length=200)),
                ('aplicado', models.BooleanField(default=False, help_text='Indica si el movimiento ya fue aplicado a la cuenta')),
                ('asiento', models.ForeignKey(help_text='Asiento contable al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='accounting.asientocontable')),
                ('cuenta', models.ForeignKey(help_text='Cuenta contable afectada', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='accounting.cuentacontable')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActivoCorriente',
            fields=[
            ],
            options={
                'verbose_name': 'Activo Corriente',
                'verbose_name_plural': 'Activos Corrientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.activo',),
        ),
        migrations.CreateModel(
            name='ActivoNoCorriente',
            fields=[
            ],
            options={
                'verbose_name': 'Activo No Corriente',
                'verbose_name_plural': 'Activos No Corrientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.activo',),
        ),
        migrations.CreateModel(
            name='PasivoCorriente',
            fields=[
            ],
            options={
                'verbose_name': 'Pasivo Corriente',
                'verbose_name_plural': 'Pasivos Corrientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.pasivo',),
        ),
        migrations.CreateModel(
            name='PasivoNoCorriente',
            fields=[
            ],
            options={
                'verbose_name': 'Pasivo No Corriente',
                'verbose_name_plural': 'Pasivos No Corrientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.pasivo',),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['fecha', 'estado'], name='accounting__fecha_e35fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['numero'], name='accounting__numero_855cd6_idx'),
        ),
    ]
